/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import ventasdao.ui.Principal;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import ventasdao.controladores.DetalleFacturaControlador;
import ventasdao.controladores.FacturaControlador;
import ventasdao.controladores.FacturaProductoControlador;
import ventasdao.controladores.FormaPagoControlador;
import ventasdao.controladores.UpdateStockControlador;
import ventasdao.dominio.Conexion;
import ventasdao.objetos.FormaPago;
import ventasdao.objetos.Cliente;
import ventasdao.objetos.DetalleFactura;
import ventasdao.ui.grilla.GrillaCliente;
import ventasdao.ui.grilla.GrillaDetalleFactura;
import ventasdao.objetos.Factura;
import ventasdao.objetos.Producto;
import static ventasdao.ui.abm.FacturaGetProducto.jtListadoProductos;
import ventasdao.ui.grilla.GrillaProducto;
/**
 *
 * @author Esteban DAlbano
 */
public class AbmFactura extends javax.swing.JInternalFrame {
    
    
    private FacturaControlador facturaControlador = new FacturaControlador();
    
    private DetalleFacturaControlador detalleFacturaControlador = new DetalleFacturaControlador();
    
    
    private GrillaDetalleFactura grillaDetalleFactura;
    private DetalleFactura detalleFactura;
    
    private DefaultComboBoxModel modelCombo;
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    private String descontar = null ;
        
    private String total = null;
         
    private double newtotal = 0;
         
    private String newtotalcadena= null;
    
    private String cantidad = null; 
    
    List<DetalleFactura> detallefacturas = new ArrayList<>();
    
    private GrillaProducto grillaProducto;
    
     TableRowSorter trs;
     
     private UpdateStockControlador updateStockControlador = new UpdateStockControlador();
     
     
        
            
    
    
    
    
    private FormaPagoControlador formaPagoControlador = new FormaPagoControlador();
    
    /**
     * Creates new form Factura
     */
    public AbmFactura() {
        initComponents();
        
        
        
        jtfTotal.setText("0");
        
        jTabbedPane1.setVisible(false); 
        
        /*ArrayList<DetalleFactura> detallefacturas = new ArrayList<DetalleFactura>();
        
        grillaDetalleFactura = new GrillaDetalleFactura(detallefacturas);
         jtListadoFacturacion.setModel(grillaDetalleFactura);
        *
        
        
        /*
         ArrayList<DetalleFactura> detallefacturas;
        try {
            detallefacturas = facturaProductoControlador.listar();
           grillaDetalleFactura = new GrillaDetalleFactura(detallefacturas);
             jtListadoFacturacion.setModel(grillaDetalleFactura);
        } catch (Exception e) {
            e.printStackTrace ();
        }
        
      */
        
         try {
           ArrayList<FormaPago> formapagos = formaPagoControlador.listar();
           modelCombo = new DefaultComboBoxModel(formapagos.toArray());
           jcbFormaPago.setModel(modelCombo);
           
       } catch (Exception ex) {
           ex.printStackTrace();
       }
        
        
        
        
        
        
        
    }
    
    
    
    
    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoFacturacion = new javax.swing.JTable();
        jbAgregarProducto = new javax.swing.JButton();
        jbAgregarCliente = new javax.swing.JButton();
        jtfNumeroFactura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfTotal = new javax.swing.JTextField();
        jcbFormaPago = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbAltaFactura = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();
        jtfObservaciones = new javax.swing.JTextField();
        jtfNombreF = new javax.swing.JTextField();
        jtfApellidoF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfClienteIF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfFecha = new javax.swing.JTextField();
        jtfPagaCon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfVuelto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jtfDescuento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfInteres = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfTCD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfTCI = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfVCD = new javax.swing.JTextField();
        jtfVCI = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jcbEDDI = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Facturacion");

        jtListadoFacturacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Precio", "Cantidad", "Producto_Id"
            }
        ));
        jtListadoFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoFacturacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoFacturacion);

        jbAgregarProducto.setText("Agregar Producto");
        jbAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarProductoActionPerformed(evt);
            }
        });

        jbAgregarCliente.setText("Agregar Cliente");
        jbAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarClienteActionPerformed(evt);
            }
        });

        jtfNumeroFactura.setEditable(false);

        jLabel1.setText("Numero de Factura");

        jLabel2.setText("Cliente");

        jcbFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Forma de pago");

        jLabel4.setText("Total $");

        jbAltaFactura.setText("Confirmar");
        jbAltaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaFacturaActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha de venta");

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jtfNombreF.setEditable(false);

        jtfApellidoF.setEditable(false);
        jtfApellidoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidoFActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre");

        jLabel7.setText("Apellido");

        jLabel8.setText("Observaciones");

        jtfClienteIF.setEditable(false);

        jLabel9.setText("Id");

        jtfFecha.setEditable(false);

        jtfPagaCon.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfPagaConCaretUpdate(evt);
            }
        });
        jtfPagaCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPagaConKeyTyped(evt);
            }
        });

        jLabel10.setText("Paga con $");

        jLabel11.setText("Vuelto $");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jtfDescuento.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfDescuentoCaretUpdate(evt);
            }
        });

        jLabel12.setText("Descuento %");

        jtfInteres.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfInteresCaretUpdate(evt);
            }
        });

        jLabel15.setText("Interes %");

        jLabel13.setText("T c/d $");

        jLabel14.setText("T c/i $");

        jLabel16.setText("vuelto $");

        jLabel17.setText("vuelto $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfInteres, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jtfDescuento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTCD, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTCI, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfVCI, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfVCD)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jtfTCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jtfTCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("F1", jPanel1);

        jcbEDDI.setText("Descuento/Interes");
        jcbEDDI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcbEDDIStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAltaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel9)
                                .addGap(10, 10, 10)
                                .addComponent(jtfClienteIF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNombreF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfApellidoF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfPagaCon)
                                            .addComponent(jtfVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jcbEDDI))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(90, 90, 90)
                                            .addComponent(jLabel8)
                                            .addGap(157, 157, 157)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jtfObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(jcbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfClienteIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNombreF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfApellidoF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfPagaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbEDDI)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAltaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getAccessibleContext().setAccessibleParent(jtListadoFacturacion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarProductoActionPerformed
        // TODO add your handling code here:
        
        //Abrir un modulo desde otro modulo

  FacturaGetProducto abmGetProducto = new FacturaGetProducto();
        Principal.jdpContenedorPrincipal.add(abmGetProducto);
        abmGetProducto.setVisible(true);
        
        
        abmGetProducto.toFront();
        abmGetProducto.setVisible(true);
    }//GEN-LAST:event_jbAgregarProductoActionPerformed

    private void jbAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarClienteActionPerformed
        // TODO add your handling code here:
        
          //Abrir un modulo desde otro modulo

        FacturaGetCliente facturaGetCliente = new FacturaGetCliente();
        Principal.jdpContenedorPrincipal.add(facturaGetCliente);
       
        
        facturaGetCliente.toFront();
        facturaGetCliente.setVisible(true);
    }//GEN-LAST:event_jbAgregarClienteActionPerformed

    
    
    
    
    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        
        
       
        modelo = (DefaultTableModel) jtListadoFacturacion.getModel();
        
        int filasele = jtListadoFacturacion.getSelectedRow();
        
        
        int factPID = Integer.parseInt(jtListadoFacturacion.getValueAt(filasele, 4).toString()); //Guardo este dato
        int factPST = Integer.parseInt(jtListadoFacturacion.getValueAt(filasele, 3).toString()); // Guardo este dato
        
        
        descontar = jtListadoFacturacion.getValueAt(filasele, 2).toString();
        
        cantidad = jtListadoFacturacion.getValueAt(filasele, 3).toString();
        
         total = jtfTotal.getText();
         
         newtotal = Double.parseDouble(total) - Double.parseDouble(descontar)* Double.parseDouble(cantidad);
         
         newtotalcadena= String.valueOf(newtotal);
        
         jtfTotal.setText(newtotalcadena);
        
          modelo.removeRow(filasele);
          
          
          //Validamos que exista una tabla activa del otro lado
          int cantfilasFGP = FacturaGetProducto.jtListadoProductos.getRowCount();
          
          if(cantfilasFGP>0) {
              
              String var = FacturaGetProducto.jcbCategorias.getSelectedItem().toString();
              
            //  if(var.equals("Todos")) {
                  
              
      //En esta parte cargo toda la tabla en un arraylist para modificar el stock y volver a poner todo en la grilla
        
        ArrayList<Producto> aOproductos = new ArrayList<>();
        
        
        
       
        
        for(int i=0;i<cantfilasFGP;i++){
            
        Producto Oproducto = new Producto();
        
        
        Oproducto.setId(Integer.parseInt(jtListadoProductos.getValueAt(i, 0).toString()));
        Oproducto.setCategoria_id(Integer.parseInt(jtListadoProductos.getValueAt(i, 1).toString()));
        Oproducto.setNombre((jtListadoProductos.getValueAt(i, 2).toString()));
        Oproducto.setDescripcion((jtListadoProductos.getValueAt(i, 3).toString()));
        Oproducto.setPrecio(Float.parseFloat(jtListadoProductos.getValueAt(i, 4).toString()));
        Oproducto.setStock(Integer.parseInt(jtListadoProductos.getValueAt(i, 5).toString()));
        Oproducto.setFechaAlta((jtListadoProductos.getValueAt(i, 6).toString()));
        
        
        
       
         if(Oproducto.getId()==factPID)
           Oproducto.setStock(Oproducto.getStock()+factPST); 
       
        
            
        aOproductos.add(Oproducto);
        
        }
        
        
        grillaProducto = new GrillaProducto(aOproductos);
        jtListadoProductos.setModel(grillaProducto);
        
        ///// Estas dos lineas me solucionaron el problema que tenia al filtrar por nombre no me mostraba despues todas las filas al seleccionar una catgoria
            trs = new TableRowSorter(jtListadoProductos.getModel());
            jtListadoProductos.setRowSorter(trs);  /////
               
       
                  
                  
             // }
              
           
              
            
          }
        
        
        
        
        /*
        detalleFactura = new DetalleFactura();
        detalleFactura.setId(Integer.parseInt(jtfId.getText()));
        
        try {
            facturaProductoControlador.eliminar(detalleFactura);
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            jtListadoFacturacion.setModel(new GrillaDetalleFactura(facturaProductoControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        //Este refresca la grilla una vez que se hizo una modificacion de lo contrario pierde referencia la grilla con los textfield
        facturaProductoControlador = new FacturaProductoControlador();
        ArrayList<DetalleFactura> detallefacturas = new ArrayList<>();

        try {
            detallefacturas = facturaProductoControlador.listar();
        } catch (Exception e) {
            e.printStackTrace ();
        }

        grillaDetalleFactura = new GrillaDetalleFactura(detallefacturas);
        jtListadoFacturacion.setModel(grillaDetalleFactura);
        
        */
        
        
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jtListadoFacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoFacturacionMouseClicked
        // TODO add your handling code here:
        
     /*   DetalleFactura detallefactura = grillaDetalleFactura.getDetalleFacturaFromRow(jtListadoFacturacion.getSelectedRow());
       
       jtfId.setText( detallefactura.getId().toString() );        */
    }//GEN-LAST:event_jtListadoFacturacionMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbAltaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaFacturaActionPerformed
        // TODO add your handling code here:
        
         Factura factura = new Factura();
        
        factura.setMonto_total(Float.parseFloat(jtfTotal.getText()));
        factura.setCliente_id(Integer.parseInt(jtfClienteIF.getText()));
        factura.setFormapago((FormaPago)(jcbFormaPago.getSelectedItem()));
        factura.setObservaciones(jtfObservaciones.getText());
       
      
        
        
       try {
           facturaControlador.crear(factura);
           //limpiarCampos();
       } catch (Exception ex) {
           Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        /// Cargo el Array del grilla factura
        
        int cantidadfilas = jtListadoFacturacion.getRowCount();
        
        for(int i=0;i<cantidadfilas;i++){
            DetalleFactura detallefactura = new DetalleFactura();
            
        detallefactura.setProducto_id(Integer.parseInt(jtListadoFacturacion.getValueAt(i, 4).toString()));  //producto_id
         //JOptionPane.showMessageDialog(null,"ProductoId"+jtListadoFacturacion.getValueAt(i, 4).toString());
        detallefactura.setCantidad(Integer.parseInt(jtListadoFacturacion.getValueAt(i, 3).toString()));   //cantidad
         //JOptionPane.showMessageDialog(null,"Cantidad="+jtListadoFacturacion.getValueAt(i, 3).toString());
        detallefactura.setFactura_id(Integer.parseInt(jtfNumeroFactura.getText())); //factura_id
            
             //JOptionPane.showMessageDialog(null,"carga el 1er elemento del arraylist cuando i="+i);
            
            detallefacturas.add(detallefactura);
       
        }
        
        
        
        
        
        try {
           detalleFacturaControlador.crear(detallefacturas);
           //limpiarCampos();
       } catch (Exception ex) {
           Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
        
       //En esta parte actualizo el stock en la base de datos un avez que se confirmo la factura
       try {
           updateStockControlador.decrementar(detallefacturas);
           //limpiarCampos();
       } catch (Exception ex) {
           Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
       } 
        
        
        
        
        
        JOptionPane.showMessageDialog(null,"La factura se creo Exitosamente!!!");
        
        
        
        
        
        
    }//GEN-LAST:event_jbAltaFacturaActionPerformed

    private void jtfApellidoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApellidoFActionPerformed

    private void jtfPagaConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPagaConKeyTyped
        // TODO add your handling code here: 
    }//GEN-LAST:event_jtfPagaConKeyTyped

    
    private void jtfPagaConCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfPagaConCaretUpdate
        // TODO add your handling code here:
        String bandera = jtfPagaCon.getText();
        
        if(bandera.equals("")){
            
        }
            
        else {
        Double total = Double.parseDouble(jtfTotal.getText());
        Double efectivo = Double.parseDouble(jtfPagaCon.getText());
        Double vueltoD = efectivo - total;
        String vueltoS = String.valueOf(vueltoD);
        jtfVuelto.setText(vueltoS);
                }
        
    }//GEN-LAST:event_jtfPagaConCaretUpdate

    private void jtfDescuentoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfDescuentoCaretUpdate
        // TODO add your handling code here:
        String bandera = jtfDescuento.getText();
        
        if(bandera.equals("")){
            
        }
        
        else {
        DecimalFormat df = new DecimalFormat("#.00");
         
        Double total = Double.parseDouble(jtfTotal.getText());
        Double porcent_descuento = Double.parseDouble(jtfDescuento.getText());
        Double efectivo = Double.parseDouble(jtfPagaCon.getText());
        Double descuento = (porcent_descuento*total)/100;
        Double totalCD = total - descuento;
        Double vueltoCD = efectivo - totalCD;
        String totalCDs = String.valueOf(df.format(totalCD));
        String vueltoCDs = String.valueOf(df.format(vueltoCD));
        jtfTCD.setText(totalCDs);
        jtfVCD.setText(vueltoCDs);
        
        }
        
    }//GEN-LAST:event_jtfDescuentoCaretUpdate

    private void jtfInteresCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfInteresCaretUpdate
        // TODO add your handling code here:
         String bandera = jtfInteres.getText();
        
        if(bandera.equals("")){
            
        }
        
        else {
        DecimalFormat df = new DecimalFormat("#.00");
         
        Double total = Double.parseDouble(jtfTotal.getText());
        Double porcent_interes = Double.parseDouble(jtfInteres.getText());
        Double efectivo = Double.parseDouble(jtfPagaCon.getText());
        Double interes = (porcent_interes*total)/100;
        Double totalCI = total + interes;
        Double vueltoCI = efectivo - totalCI;
        String totalCIs = String.valueOf(df.format(totalCI));
        String vueltoCIs = String.valueOf(df.format(vueltoCI));
        jtfTCI.setText(totalCIs);
        jtfVCI.setText(vueltoCIs);
        
        }
        
    }//GEN-LAST:event_jtfInteresCaretUpdate

    private void jcbEDDIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcbEDDIStateChanged
        // TODO add your handling code here:
        if(jcbEDDI.isSelected())
        jTabbedPane1.setVisible(true);
        else{
        jTabbedPane1.setVisible(false);    
        }
    }//GEN-LAST:event_jcbEDDIStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAgregarCliente;
    private javax.swing.JButton jbAgregarProducto;
    private javax.swing.JButton jbAltaFactura;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JCheckBox jcbEDDI;
    private javax.swing.JComboBox<String> jcbFormaPago;
    public static javax.swing.JTable jtListadoFacturacion;
    public static javax.swing.JTextField jtfApellidoF;
    public static javax.swing.JTextField jtfClienteIF;
    private javax.swing.JTextField jtfDescuento;
    public static javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfInteres;
    public static javax.swing.JTextField jtfNombreF;
    public static javax.swing.JTextField jtfNumeroFactura;
    public static javax.swing.JTextField jtfObservaciones;
    private javax.swing.JTextField jtfPagaCon;
    private javax.swing.JTextField jtfTCD;
    private javax.swing.JTextField jtfTCI;
    public static javax.swing.JTextField jtfTotal;
    private javax.swing.JTextField jtfVCD;
    private javax.swing.JTextField jtfVCI;
    private javax.swing.JTextField jtfVuelto;
    // End of variables declaration//GEN-END:variables
}



/*Idea de la implementacion
creo una tabla factura donde tiene un ID unico y un nombre de cliente
luego otra tabla detalle factura que esta relacionada con un Fk factura_id
referenciada a la tabla factura, se van igresando registros en detalle factura y todos esos
registros estaran asociados a la AbmFactura Id correspondiente
luego cuando cree una nueva factura se incrementa el registro de factura y ese
sera el factura_id que se usara en la tabla detalle factura para los nuevos registros y se repite el
proceso para las proximas facturas creadas*/