/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;

//import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.table.DefaultTableModel;

import java.util.ArrayList;
import ventasdao.controladores.LoginUserControlador;

import ventasdao.objetos.Usuario;


import ventasdao.ui.grilla.GrillaUsuario;


import java.io.FileWriter;
import java.net.InetAddress;
import java.net.NetworkInterface;

/**
 *
 * @author Esteban DAlbano
 */
public class AbmUsuario extends javax.swing.JInternalFrame {
    
    
    private Usuario usuario;
    private GrillaUsuario grillaUsuario;
    private LoginUserControlador loginUser = new LoginUserControlador();
    
    
    
    public AbmUsuario() {
        
        initComponents();
        
        ArrayList<Usuario> usuarios;
        try {
            usuarios = loginUser.listar();
            grillaUsuario = new GrillaUsuario(usuarios);
             jtListadoUsuarios.setModel(grillaUsuario);
        } catch (Exception e) {
            e.printStackTrace ();
        }

        
        
        //Consigo la MAC del PC y lo ponog en el java text field
         mac p = new mac();
         jtfMac.setText(p.conseguirMAC());
        
       
         
    }
    
    public void limpiarCampos(){
    
        jtfId.setText("");
        jtfNombre.setText("");
        jtfClave.setText("");
        jtfTipo.setText("");
        
          
    }

    /*Clase mac y funcion conseguirMAC para obtener la MAC del PC*/
    public class mac {

    
     public String conseguirMAC(){
            StringBuilder sb = new StringBuilder();
  NetworkInterface a; String linea;
  try {
   a = NetworkInterface.getByInetAddress(InetAddress.getLocalHost());
   byte[] mac = a.getHardwareAddress();
   

   for (int i = 0; i < mac.length; i++) {
    sb.append(String.format("%02X%s", mac[i], (i < mac.length - 1) ? "-" : ""));  
   } 
   FileWriter fwriter = new FileWriter("mac.dat");
   fwriter.write("MAC: " + sb.toString());
   fwriter.close();
   
 //  lmac.setText("SE ha registrado la MAC exitosamente.");
  } catch (Exception e) {
   e.printStackTrace(); 
  }
  return ""+sb.toString();
 }
    
    }
    
   

    /**
     * Creates new form AbmUsuario
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtListadoUsuarios = new javax.swing.JTable();
        jbAltaUsuario = new javax.swing.JButton();
        jbModificarUsuario = new javax.swing.JButton();
        jbBajaUsuario = new javax.swing.JButton();
        jtfId = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfClave = new javax.swing.JTextField();
        jtfTipo = new javax.swing.JTextField();
        jtfEstado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfMac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        setTitle("Usuarios");
        setToolTipText("");

        jtListadoUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtListadoUsuarios);

        jbAltaUsuario.setText("Agregar");
        jbAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaUsuarioActionPerformed(evt);
            }
        });

        jbModificarUsuario.setText("Modificar");
        jbModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarUsuarioActionPerformed(evt);
            }
        });

        jbBajaUsuario.setText("Eliminar");
        jbBajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaUsuarioActionPerformed(evt);
            }
        });

        jtfId.setEditable(false);
        jtfId.setEnabled(false);

        jtfEstado.setEditable(false);
        jtfEstado.setEnabled(false);

        jLabel1.setText("Id");

        jLabel2.setText("Nombre");

        jLabel3.setText("Clave");

        jLabel4.setText("Tipo");

        jLabel5.setText("Estado");

        jtfMac.setEditable(false);
        jtfMac.setEnabled(false);

        jLabel6.setText("Mac Adress");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfMac, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbModificarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaUsuarioActionPerformed
        // TODO add your handling code here:
         usuario = new Usuario();
        usuario.setId(Integer.parseInt(jtfId.getText()));
        
        try {
            loginUser.eliminar(usuario);
        } catch (Exception ex) {
            Logger.getLogger(AbmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            jtListadoUsuarios.setModel(new GrillaUsuario(loginUser.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        //Este refresca la grilla una vez que se hizo una modificacion de lo contrario pierde referencia la grilla con los textfield
        loginUser = new LoginUserControlador();
        ArrayList<Usuario> usuarios = new ArrayList<>();

        try {
            usuarios = loginUser.listar();
        } catch (Exception e) {
            e.printStackTrace ();
        }

        grillaUsuario = new GrillaUsuario(usuarios);
        jtListadoUsuarios.setModel(grillaUsuario);
        
        
        //Esto limpia campos
        jtfNombre.setText("");
        jtfClave.setText("");
       
        jtfTipo.setText("");
        jtfEstado.setText("");
       
        
    }//GEN-LAST:event_jbBajaUsuarioActionPerformed

    private void jbModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            
            usuario = new Usuario();
            
            usuario.setId( Integer.parseInt( jtfId.getText() ) );
            usuario.setNombre( jtfNombre.getText() );
            usuario.setClave( jtfClave.getText() );
            usuario.setTipo( jtfTipo.getText() );
            
            
            loginUser.modificar(usuario);
        } 
        catch (Exception ex) {
            Logger.getLogger(AbmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            jtListadoUsuarios.setModel( new GrillaUsuario( loginUser.listar() ));
        } 
        catch (Exception ex) {
            Logger.getLogger(AbmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //Este refresca la grilla una vez que se hizo una modificacion de lo contrario pierde referencia la grilla con los textfield
        loginUser = new LoginUserControlador();
        ArrayList<Usuario> usuarios = new ArrayList<>();

        try {
            usuarios = loginUser.listar();
        } catch (Exception e) {
            e.printStackTrace ();
        }

        grillaUsuario = new GrillaUsuario(usuarios);
        jtListadoUsuarios.setModel(grillaUsuario);
        
        
        //Esto limpia campos
        jtfNombre.setText("");
        jtfClave.setText("");
       
        jtfTipo.setText("");
        jtfEstado.setText("");
        
        
    }//GEN-LAST:event_jbModificarUsuarioActionPerformed

    private void jbAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaUsuarioActionPerformed
        // TODO add your handling code here:
        usuario = new Usuario();

        usuario.setNombre(jtfNombre.getText());
        usuario.setClave(jtfClave.getText());
        usuario.setTipo(jtfTipo.getText());
        usuario.setEstado("desconectado"); //Al crear un usuario por defecto tendra el valor desconectado
  
        usuario.setPc_mac(jtfMac.getText());
        
        try {
            loginUser.crear(usuario);
            
        } catch (Exception ex) {
            Logger.getLogger(AbmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Este refresca la grilla una vez que se hizo una modificacion de lo contrario pierde referencia la grilla con los textfield
        loginUser = new LoginUserControlador();
        ArrayList<Usuario> usuarios = new ArrayList<>();

        try {
            usuarios = loginUser.listar();
        } catch (Exception e) {
            e.printStackTrace ();
        }

        grillaUsuario = new GrillaUsuario(usuarios);
        jtListadoUsuarios.setModel(grillaUsuario);
        
        
        //Esto limpia campos
        jtfId.setText("");
        jtfNombre.setText("");
        jtfClave.setText("");
        jtfTipo.setText("");
        jtfEstado.setText("");
         //La mac no se limpia porque es la misma siempre y debe estar fija en el jtfMac para capturarla con cada alta
        
    }//GEN-LAST:event_jbAltaUsuarioActionPerformed

    private void jtListadoUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoUsuariosMouseClicked
        // TODO add your handling code here:
        Usuario usuario = grillaUsuario.getUsuarioFromRow(jtListadoUsuarios.getSelectedRow());
       
       jtfId.setText( usuario.getId().toString() );
        jtfNombre.setText(usuario.getNombre());
       jtfClave.setText(usuario.getClave());
       jtfTipo.setText( usuario.getTipo() );
       jtfEstado.setText( usuario.getEstado() );
    }//GEN-LAST:event_jtListadoUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAltaUsuario;
    private javax.swing.JButton jbBajaUsuario;
    private javax.swing.JButton jbModificarUsuario;
    private javax.swing.JTable jtListadoUsuarios;
    private javax.swing.JTextField jtfClave;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfMac;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTipo;
    // End of variables declaration//GEN-END:variables

}